#!/bin/bash

IP=hosthere

/tmp/ebdse/ebdse activity type=cql yaml=telemetry tags=group:schema replication="{'class':'NetworkTopologyStrategy','AWS':3, 'Azure': 1, 'GCP': 1}" host=$IP username=assethub password=assethub

/tmp/ebdse/ebdse activity type=cql yaml=telemetry cycles=1000000 tags=group:write host=$IP username=assethub password=assethub threads=20
